region = "us-east-1"
project = "devts"
bucket_name="devtsbkt2241"
s3_acl="private"
key_name="index.html"
source_path="C:\\Software\\Data\\Important\\Devops\\Valaxy_AWS\\terraform-code\\modules\\s3\\index.html"